### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by visaolangle00** [flithy35/FootballApp#2]
Can you give me the database file, so I can run the project and learn from it.

**Comment by dunicadavid** [comment]
[footbalapp.zip](https://github.com/dunicadavid/FootballApp/files/9053873/footbalapp.zip)
here is the database, enjoy

**Comment by visaolangle00** [comment]
> [footbalapp.zip](https://github.com/dunicadavid/FootballApp/files/9053873/footbalapp.zip) here is the database, enjoy

thank you.

**Comment by visaolangle00** [comment]
> [footbalapp.zip](https://github.com/dunicadavid/FootballApp/files/9053873/footbalapp.zip) here is the database, enjoy


can you send me the sql file, the other files i don't know how to convert. Thank you very much.

**Comment by visaolangle00** [comment]
> can you send me the sql file, the other files i don't know how to convert. Thank you very much.



> [footbalapp.zip](https://github.com/dunicadavid/FootballApp/files/9053873/footbalapp.zip) here is the database, enjoy

**Comment by visaolangle00** [comment]
> [footbalapp.zip](https://github.com/dunicadavid/FootballApp/files/9053873/footbalapp.zip) here is the database, enjoy

can you send me the sql file, the other files i don't know how to convert. Thank you very much.
